### PR TITLE
Fixed Tweet Colors (Hopefully)

### PR DESCRIPTION
**Pull request by Zarrck**

### CODE REVIEW

**Comment by nomisum** [comment]
wtf

**Comment by DerZade** [comment]
I would suggest to reject the proposal. 
What do you think @nomisum ?

**Comment by nomisum** [comment]
If blue turns out too omnipresent I suggest reverting to something like this instead of adler orange
Group 4 3

**Comment by Zarrck** [comment]
The Adler Orange was more of a bandaid solution anyway. The gray probably works better than Adler Orange. And everything is better then the abhorrent Twitter blue.

**Comment by DerZade** [comment]
@Zarrck fyi

**Pull request closed without merging**
